# Prometheus Server 1 - monitor itself
global:
  scrape_interval: 15s
  evaluation_interval: 1s
  external_labels:
    monitor: 'prometheus'

# Rules and alerts are read from the specified file(s)
rule_files:
  - rules.yml

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # Alertmanager's default port is 9093
        - localhost:9093

scrape_configs:
  # Monitor itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  # Monitor static list of sites
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ec2-52-23-196-188.compute-1.amazonaws.com:9100']
  
  # Auto-discover ec2 instances
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAYZSTJE23FZLFSD4R
        secret_key: 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
        port: 9100